# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Drape < Formula
  desc "CLI for uploading test results and coverage to Drape"
  homepage "https://drape.io"
  version "0.1.3"
  license "MPL-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/drape-io/drape-cli/releases/download/v0.1.3/drape_darwin_amd64.tar.gz"
      sha256 "1dbd971c452424577ae12eded83a1a2bd7bec5942a3ffe9c3c4dbfffd1f64dd1"

      define_method(:install) do
        bin.install "drape"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/drape-io/drape-cli/releases/download/v0.1.3/drape_darwin_arm64.tar.gz"
      sha256 "485676bf4425698d2d1174a659adb132c8b8977bdaf4191e066169a7094ea4e8"

      define_method(:install) do
        bin.install "drape"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/drape-io/drape-cli/releases/download/v0.1.3/drape_linux_amd64.tar.gz"
      sha256 "28ec5acd08466c9c846f9f98d46c9c96c8f7081738f22dc2c24f0df5bcf4c765"
      define_method(:install) do
        bin.install "drape"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/drape-io/drape-cli/releases/download/v0.1.3/drape_linux_arm64.tar.gz"
      sha256 "50e8184bd0664af2d31ea9d6800763de52e255258f90bd4683ef79173c5285eb"
      define_method(:install) do
        bin.install "drape"
      end
    end
  end

  test do
    system "#{bin}/drape", "version"
  end
end
