# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Drape < Formula
  desc "CLI for uploading test results and coverage to Drape"
  homepage "https://drape.io"
  version "0.1.1"
  license "MPL-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/drape-io/drape-cli/releases/download/v0.1.1/drape_0.1.1_darwin_amd64.tar.gz"
      sha256 "8a3083816c88e3574f9938f486456a1ac151c0581681fcb5bffbb9af9302f870"

      define_method(:install) do
        bin.install "drape"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/drape-io/drape-cli/releases/download/v0.1.1/drape_0.1.1_darwin_arm64.tar.gz"
      sha256 "6fc8e17c1fca95c125de6ea94dc88574149cfc9eae00489258fe9a388c813d87"

      define_method(:install) do
        bin.install "drape"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/drape-io/drape-cli/releases/download/v0.1.1/drape_0.1.1_linux_amd64.tar.gz"
      sha256 "fd7d0712767e7f066e22c5b63f75d8e85108efe75a2b44427d259eb7e6c9d97f"
      define_method(:install) do
        bin.install "drape"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/drape-io/drape-cli/releases/download/v0.1.1/drape_0.1.1_linux_arm64.tar.gz"
      sha256 "7e2aa48bc73a39aaadaffa8dca6afaeb60b33547d2615c63d83345e7e3e5a707"
      define_method(:install) do
        bin.install "drape"
      end
    end
  end

  test do
    system "#{bin}/drape", "version"
  end
end
